version: '3'
services:
  node:
    image: qnib/plain-elasticsearch@sha256:25fe9086b2b159e662a10740c55ac7de7c410b2b3ba449e33f9c3849b4794bbf
    hostname: '{{.Service.Name}}.{{.Task.Slot}}.{{.Task.ID}}'
    environment:
      SWARM_SERVICE_NAME: '{{.Service.Name}}'
      SWARM_TASK_SLOT: '{{.Task.Slot}}'
      SWARM_TASK_ID: '{{.Task.ID}}'
      SWARM_NODE_ID: '{{.Node.ID}}'
    ports:
     - "9200:9200"
    deploy:
      #mode: global
      replicas: 1
