version: '3'
services:
  master:
    image: qnib/plain-elasticsearch:1.7.6
    ports:
      - "9200:9200"
      - "9300:9300"
    deploy:
      resources:
        # Only one master for now
        replicas: 1
        limits:
          cpus: '1'
          memory: 768M
      update_config:
        parallelism: 1
        delay: 15s
      restart_policy:
        condition: on-failure
    environment:
      ES_HEAP_MAX: "512m"
      ES_HEAP_MIN: "512m"
      ES_NODE_MASTER: "true"
      ES_NODE_DATA: "true"
