#node.rack: ${RACK_ENV_VAR}
cluster.name: ES_CLUSTER_NAME
node.name: ES_NODE_NAME
node.master: ES_MASTER_NODE
node.data: ES_DATA_NODE
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
#discovery.zen.ping.unicast.hosts: localhost
network.bind_host: 0.0.0.0
#network.publish_host: _local_

